merchex/blog/urls.py
# Dans urls.py de votre application
from django.conf import settings
from django.urls import path, include
from . import views
from .views import BlogPost, BlogNotes, BlogProject


from django.conf.urls.static import static

from django.conf import settings

# from .views import BlogList
# from .views import VueAppView
from django.views.generic import TemplateView

app_name = "blog"

urlpatterns = [
    path('post/', BlogPost.as_view(), name='post_list'),
    path('moi', views.Blog_Profil, name='blog_profil'),
    path('projets/', BlogProject.as_view(), name='blog_projects'),
    path('notes/', BlogNotes.as_view(), name='blog_Notes'),
    path('comment_ont_fait', views.Blog_How, name='blog_How'),
    path('labo', views.Blog_Lab, name='blog_Labo'),
    # path('', BlogIndex.as_view(), name='index'),

    # path('spotify', views.Spotify_Playlist, name='spotify')
    # path('', VueAppView.as_view(), name='app'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

merchex/merchex/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path
from blog import views
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/", include('blog.urls')),
    path("blog/", include("blog.urls")),
    # Point d'entrée pour Vue.js
    path("", TemplateView.as_view(template_name="index.html")),

    # path('accounts/', include('allauth.urls')),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

merchex/blog/models.py
from django.db import models
from django.utils import timezone
# from rest_framework import viewsets


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Post(models.Model):
    class Language(models.TextChoices):
        PHP = 'PHP', 'PHP'
        JS = 'JS', 'JavaScript'
        PYTHON = 'PYTHON', 'Python'
        HTML = 'HTML', 'HTML'
        CSS = 'CSS', 'CSS'
        JAVA = 'JAVA', 'java'

    title = models.CharField(max_length=100)
    content = models.TextField()
    images = models.ImageField(blank=True, null=True, upload_to='blog/images')
    created_at = models.DateTimeField(auto_now_add=True)
    like = models.IntegerField(default=0)
    dislike = models.IntegerField(default=0)
    language = models.CharField(choices=Language.choices, max_length=10)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='posts', blank=True, null=True)

    def __str__(self):
        return self.title


class Project(models.Model):
    class Langage(models.TextChoices):
        HTML_CSS = 'HTML/CSS', 'HTML/CSS'
        PHP = 'PHP', 'PHP'
        JS = 'JS', 'JavaScript'
        PYTHON = 'PYTHON', 'Python'

    class FramworkFront(models.TextChoices):
        VUEJS = 'Vue.js'

    class FramworkBack(models.TextChoices):
        NODESJS = 'Nodes.js'
        SYMPHONY = 'Symfony'
        DJANGO = 'Django'

    title = models.CharField(max_length=100)
    description = models.TextField()
    language = models.CharField(max_length=50, choices=Langage.choices)
    frameworkfront = models.CharField(
        max_length=10, choices=FramworkFront.choices, blank=True, null=True)
    frameworkback = models.CharField(
        max_length=10, choices=FramworkBack.choices, blank=True, null=True)
    new = models.BooleanField()
    date_completed = models.DateField(blank=True, null=True)
    project_link = models.URLField(blank=True, null=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.title


# class PostViewSet(viewsets.ReadOnlyModelViewSet):
#     queryset = Post.objects.all()
class Notes(models.Model):
    title = models.TextField()
    content = models.TextField()
    images = models.ImageField(blank=True, null=True)
    public = models.BooleanField(default=False)
    private = models.BooleanField(default=False)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='notes', blank=True, null=True)

    def __str__(self):
        return self.title

merchex/blog/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.db.models import Q
from rest_framework.permissions import IsAuthenticated
from django.http import Http404

from .models import Post
from .models import Project
from .models import Notes
import requests
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import PostSerializer
from .serializers import NotesSerializer
from .serializers import ProjectSerializer
from django.core.paginator import Paginator

# import spotipy
from django.conf import settings

# from spotipy.oauth2 import SpotifyOAuth

from .spotify import get_spotify_token, get_spotify_playlist


class BlogPost(APIView):
    def get(self, request, format=None):
        search_query = request.GET.get('search', None)

        if search_query:
            posts = Post.objects.filter(
                Q(title__icontains=search_query) |
                Q(content__icontains=search_query) |
                Q(language__icontains=search_query) |
                Q(category__name__icontains=search_query)

            )
        else:
            posts = Post.objects.all().order_by('id')  # Assurez-vous d'avoir order_by ici

        paginator = Paginator(posts, 4)  # 4 posts par page
        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
        serializer = PostSerializer(page_obj, many=True)

        return Response({
            'posts': serializer.data,
            'num_pages': paginator.num_pages,
            'current_page': page_obj.number
        })


class BlogNotes(APIView):
    def get(self, request, format=None):
        search_query = request.GET.get('search', None)

        if search_query:
            notes = Notes.objects.filter(
                Q(title__icontains=search_query) |
                Q(content__icontains=search_query)
            )
        else:
            notes = Notes.objects.all().order_by('id')

        paginator = Paginator(notes, 6)  # 4 notes par page
        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)
        serializer = NotesSerializer(page_obj, many=True)

        return Response({
            'notes': serializer.data,
            'num_pages': paginator.num_pages,
            'current_page': page_obj.number
        })

# def vue_index(request):
#     return render(request, "app.html")


def Blog_Profil(request):
    return render(request, 'posts/moi.html')


class BlogProject(APIView):
    def get(self, request, format=None):
        projects = Project.objects.all()
        serializer = ProjectSerializer(projects, many=True)
        return Response(serializer.data)



def Blog_How(request):
    post = Post.objects.all()  # Récupérer tous les tutoriels
    return render(request, 'posts/explains.html', {'posts': post})


def Blog_Lab(request):
    return render(request, 'posts/labo.html')


# class BlogIndex(APIView):
#     def get(self, request, format=None):
#         latest_posts = Post.objects.all().order_by('-created_at')[:5]
#         latest_notes = Notes.objects.all().order_by('-created_at')[:5]
#         latest_projects = Project.objects.all().order_by('-created_at')[:5]

#         posts_serializer = PostSerializer(latest_posts, many=True)
#         notes_serializer = NotesSerializer(latest_notes, many=True)
#         projects_serializer = ProjectSerializer(latest_projects, many=True)

#         return Response({
#             'latest_posts': posts_serializer.data,
#             'latest_notes': notes_serializer.data,
#             'latest_projects': projects_serializer.data,
#         })

merchex/blog/templates/posts/base.html
{% load static %}

<html>
    <head>
        <title>blog</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        {% comment %} <link rel="stylesheet" href="{% static 'listings/styles.css' %}" /> {% endcomment %}
        <link rel="stylesheet" href="{% static 'blog/style.css' %}">
        <script src="{% static 'blog/js/script.js' %}"></script>
        <link rel="stylesheet" href="{% static 'vue/css/app.css' %}">


    </head>
    <body>
        <div id="app"></div>
        <script src="{% static 'vue/js/app.js' %}"></script>
      
        {% include "posts/partiels/navbar.html" %}

        {% block content %}{% endblock %}

      
    </body>
</html>

merchex/blog/templates/posts/explains.html
{% extends "posts/base.html" %}
{% load static %}
{% block content %}


<div class="posts">
    {% for post in posts %}
        {% include "posts/partiels/post.html" %}
    {% empty %}
        <p>No posts available.</p>
    {% endfor %}
</div>

{% endblock %}

merchex/blog/templates/posts/index.html
{% extends 'posts/base.html' %}


{% block content %}
{% include "posts/partiels/spotify.html" %}
    <div class="container">

        <h1>posts</h1>
        <div class="posts">
            {% for post in posts %}
                {% include "posts/partiels/post.html" %}
            {% empty %}
                <p>No posts available.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

merchex/blog/templates/posts/moi.html
{% extends "posts/base.html" %}
{% load static %}

{% block content %}
    <button class="button">bouton<button>
    <div class="recto">
        <div class="containercv">
    
        <div class="sidebar">
                    <div class="contact-info">
                        <p>Chagny</p>
                        <p>0627237610</p>
                        <p>guillaury.gv40@gmail.com</p>
                        <p><a href="https://github.com/Eyery21">github.com/Eyery21</a></p>
                    </div>
                    <div class="skills">
                        <h3>Compétences</h3>
                        <p>FRONT-END: React/Vue.js</p>
                        <p>BACK-END: Nodejs / Django / Symfony</p>
                        <p>Languages: Javascript / Python / Java / PHP / SQL</p>
                        <p>Mobile: Kotlin</p>
                        <p>Database: MongoDB/Mysql</p>
                    </div>
                    <div class="skills">
                        <h3>soft skills</h3>
                        <p>curiosité</p>
                        <p>adaptabilité</p>
                        <p>travail d'équipe</p>
                        <p>anticipation</p>
                        <p>patience</p>
                    </div>
                    <div class="interests">
                        <h3>Centres d'Intérêt</h3>
                        <p>Cinéma, jeux-vidéos</p>
                    </div>
        </div>
        <div class="main-content">
                    <div class="profile">
                        <h1>Profil Professionnel</h1>
                        <p>Futur étudiant en Pré-Msc à Epitech en septembre 2024, en recherche d'une alternance à partir de janvier 2025 pour une durée de 32 mois.</p>
                    </div>
                    <div class="experience">
                        <h2>Parcours Professionnel</h2>
                        <ul>
                            <li>Cariste, Tempo - Chalon-sur-Saône - Intérim</li>
                            <li>Cariste, Leader Intérim - Nantes - CDI</li>
                        </ul>
                    </div>
                    <div class="projects">
                        <h2>Projets Réalisés</h2>
                        <p>OpenClassrooms, 3W Academy, Autre</p>
                    </div>
                    <div class="education">
                        <h2>Certificats, Formations</h2>
                        <p>Développeur Web et Mobile (2022)</p>
                    </div>
                </div>
        </div>
    </div>
    <div class="verso">
        <div class="containercv">
            <p>rthdtkdtyjsdrthr</p>
    
        </div>
    </div>
{% endblock %}

merchex/blog/templates/posts/notes.html
{% extends "posts/base.html" %}
{% load static %}

{% block content %}
    <div class="windows">
        <div class="allprojects">
            {% for note in notes %}
            <div class="projet">
                <h2>{{ note.title }}</h2>
                <p>{{ note.content }}</p>
                <p>{{ note.created_at }}</p>
                <p>{{ note.category }}</p>
            </div>
                {% empty %}
                <p>No projects available.</p>
            {% endfor %}
            
        </div>
    </div>
{% endblock %}

merchex/blog/templates/posts/partiels/navbar.html
<nav class="navbar">
    <ul>
        <li><a href="{% url 'blog:blog_index' %}">acceuil</a></li>
        <li><a href="{% url 'blog:blog_profil' %}">Moi</a></li>
        <li><a href="{% url 'blog:blog_projects' %}"></a>projets</li>
        <li><a href="{% url 'blog:blog_Notes' %}"></a>notes</li>
        <li><a href="{% url 'blog:blog_How' %}"></a>comment ont fait ?</li>
        <li><a href=""></a>templates</li>
        <li><a href="{% url 'blog:blog_Labo' %}"></a>labo</li>
    </ul>
</nav>

merchex/blog/templates/posts/partiels/post.html
    <div class="tutorial">
        <h2>{{ post.title }}</h2>
        <p>{{ post.content }}</p>
        <p>{{ post.created_at }}</p>
        <p>{{ post.category }}</p>
    </div>

merchex/blog/templates/posts/partiels/spotify.html
<div class="music-player">

 </div>
 <iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/3Fh1AmyIX5Xnc1tNHJnYuM?utm_source=generator" 
 width="30%" 
 height="100" 
 frameBorder="0" 
 allowfullscreen="" 
 allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" 
 loading="lazy">
</iframe>
</div>

merchex/blog/templates/posts/projets.html
{% extends "posts/base.html" %}
{% load static %}

{% block content %}
    <div class="windows">
        <div class="allprojects">
            {% for project in projects %}
            <div class="projet">
                <h2>{{ project.title }}</h2>
                <p>{{ project.content }}</p>
                <p>{{ project.created_at }}</p>
                <p>{{ project.category }}</p>
            </div>
                {% empty %}
                <p>No projects available.</p>
            {% endfor %}
            
        </div>
    </div>
{% endblock %}

templates/posts/vue_index.html
<!doctype html><html lang=""><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/favicon.ico"><title>frontend</title><script defer="defer" src="/js/chunk-vendors.59fe12b6.js"></script><script defer="defer" src="/js/app.15a56823.js"></script><link href="/css/app.2cf79ad6.css" rel="stylesheet"></head><body><noscript><strong>We're sorry but frontend doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div></body></html>